import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import axios from 'axios';
import { BarChart3, BriefcaseBusiness, Building2, CalendarDays, GraduationCap, LayoutDashboard, Menu, Search, Settings2, Users, X } from 'lucide-react';
import './styles.css';

const api = axios.create({ baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api' });
const service = (path) => ({ list: () => api.get(path).then(r => r.data), one: id => api.get(`${path}/${id}`).then(r => r.data) });
const studentsApi = service('/students'), companiesApi = service('/companies'), jobsApi = service('/jobs'), applicationsApi = service('/applications'), interviewsApi = service('/interviews'), offersApi = service('/offers'), dashboardApi = service('/dashboard/stats');
const nav = [
  ['/', 'Overview', LayoutDashboard], ['/students', 'Students', Users], ['/companies', 'Companies', Building2],
  ['/jobs', 'Jobs', BriefcaseBusiness], ['/applications', 'Applications', BarChart3], ['/interviews', 'Interviews', CalendarDays], ['/offers', 'Offers', GraduationCap]
];
function useFetch(loader, initial = []) { const [data, setData] = useState(initial), [state, setState] = useState('loading'); useEffect(() => { let live = true; setState('loading'); loader().then(x => live && (setData(x), setState('ready'))).catch(() => live && setState('error')); return () => { live = false; }; }, []); return { data, state }; }
function App() { const [open, setOpen] = useState(false); return <div className="app"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark">P</div><div><b>Placement Portal</b><small>Career & Recruitment</small></div><button className="icon-btn mobile-close" onClick={() => setOpen(false)}><X size={18}/></button></div><nav>{nav.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setOpen(false)} className={({isActive}) => isActive ? 'active' : ''}><Icon size={18}/>{label}</NavLink>)}</nav><div className="sidebar-foot"><Settings2 size={17}/> Workspace settings</div></aside><main><header><button className="icon-btn mobile-menu" onClick={() => setOpen(true)}><Menu/></button><div><span className="eyebrow">PLACEMENT OPERATIONS</span><h1>Student Career & Recruitment Management</h1></div><div className="header-actions"><div className="search"><Search size={16}/><span>Search workspace</span><kbd>⌘ K</kbd></div><div className="avatar">PO</div></div></header><section className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/students" element={<ListPage title="Students" subtitle="Manage student talent and placement readiness" loader={studentsApi.list} columns={['name','email','course','graduationYear','cgpa']}/>} /><Route path="/students/:id" element={<StudentDetails/>}/><Route path="/companies" element={<ListPage title="Companies" subtitle="Your employer network and hiring partners" loader={companiesApi.list} columns={['name','industry','location','email']}/>} /><Route path="/jobs" element={<ListPage title="Jobs" subtitle="Open roles and active placement drives" loader={jobsApi.list} columns={['title','companyName','employmentType','location','salaryMin','applicationDeadline']}/>} /><Route path="/applications" element={<Applications/>}/><Route path="/interviews" element={<ListPage title="Interviews" subtitle="Coordinate upcoming interview rounds" loader={interviewsApi.list} columns={['studentName','jobTitle','companyName','appliedAt','status']}/>} /><Route path="/offers" element={<ListPage title="Offers" subtitle="Track offers and joining outcomes" loader={offersApi.list} columns={['studentName','jobTitle','companyName','appliedAt','status']}/>} /></Routes></section></main></div> }
function Dashboard() { const { data: raw, state } = useFetch(() => dashboardApi.list(), {}); const s = raw || {}; const cards = [['Total students', s.students, Users, 'blue'], ['Companies', s.companies, Building2, 'purple'], ['Open jobs', s.openJobs ?? s.jobs, BriefcaseBusiness, 'orange'], ['Applications', s.applications, BarChart3, 'teal'], ['Shortlisted', s.shortlisted, Users, 'green'], ['Interviews', s.interviews, CalendarDays, 'pink'], ['Selected', s.selected, GraduationCap, 'indigo'], ['Offers', s.offers, BriefcaseBusiness, 'yellow']]; return <><div className="welcome"><div><span className="eyebrow">PLACEMENT OPERATIONS</span><h2>Good morning, placement team <span>✦</span></h2><p>Here’s what’s happening across your recruitment pipeline today.</p></div><button className="primary">+ Add new record</button></div>{state === 'error' && <Notice text="The backend is unavailable. Start Spring Boot on port 8080 to load live data."/>}<div className="stats-grid">{cards.map(([label,value,Icon,color]) => <div className="stat-card" key={label}><div className={`stat-icon ${color}`}><Icon size={19}/></div><span>{label}</span><strong>{value ?? 0}</strong><small className="muted">Live from API</small></div>)}</div><div className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h3>Recruitment pipeline</h3><p>Candidate movement across active applications</p></div><button className="ghost">Last 30 days⌄</button></div><div className="pipeline">{[['Applied',s.applications,'blue'],['Shortlisted',s.shortlisted,'purple'],['Interview',s.interviews,'orange'],['Selected',s.selected,'green']].map(([x,n,c],i)=><React.Fragment key={x}><div className="stage"><div className={`stage-dot ${c}`}></div><b>{n || 0}</b><span>{x}</span></div>{i<3&&<div className="arrow">→</div>}</React.Fragment>)}</div></div><div className="panel"><div className="panel-head"><div><h3>Selection statistics</h3><p>Application outcome mix</p></div></div><div className="donut-wrap"><div className="donut"></div><div className="legend"><span><i className="dot green"></i>Selected <b>{s.selected || 0}</b></span><span><i className="dot purple"></i>Shortlisted <b>{s.shortlisted || 0}</b></span><span><i className="dot gray"></i>In review <b>{Math.max(0,(s.applications||0)-(s.selected||0)-(s.shortlisted||0))}</b></span></div></div></div></div></> }
function Notice({text}) { return <div className="notice">{text}</div> }
function ListPage({title,subtitle,loader,columns}) { const {data,state}=useFetch(loader); const [query,setQuery]=useState(''); const rows=Array.isArray(data)?data:data.content||[]; const filtered=rows.filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase()))); return <><div className="page-head"><div><span className="eyebrow">DIRECTORY</span><h2>{title}</h2><p>{subtitle}</p></div><button className="primary">+ Add {title.slice(0,-1)}</button></div><div className="toolbar"><div className="input"><Search size={16}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="ghost">Filter ▾</button><button className="ghost">Sort ↕</button></div>{state==='error'?<Notice text="Could not load this data. Check that the backend and MySQL are running."/>:state==='loading'?<div className="loading">Loading {title.toLowerCase()}…</div>:filtered.length===0?<div className="empty">No {title.toLowerCase()} found.<br/><small>Try changing your search or add a new record.</small></div>:<div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replace(/([A-Z])/g,' $1')}</th>)}<th>Actions</th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c}>{c==='status'?<span className="badge">{r[c]}</span>:String(r[c]??'—')}</td>)}<td><button className="link">View</button></td></tr>)}</tbody></table></div>}</> }
function Applications(){return <ListPage title="Applications" subtitle="Track candidate progress from apply to offer" loader={applicationsApi.list} columns={['studentName','jobTitle','companyName','appliedAt','status']}/>}
function StudentDetails(){const {id}=useParams(); const {data,state}=useFetch(()=>studentsApi.one(id),{}); return <>{state==='loading'?<div className="loading">Loading student…</div>:state==='error'?<Notice text="Student not found or backend unavailable."/>:<div className="detail"><button className="link" onClick={()=>history.back()}>← Back to students</button><div className="detail-card"><div className="avatar large">{data.name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h2>{data.name}</h2><p>{data.email} · {data.course}</p></div></div><div className="panel"><h3>Profile overview</h3><div className="detail-grid"><span>Graduation year<b>{data.graduationYear}</b></span><span>CGPA<b>{data.cgpa}</b></span><span>Phone<b>{data.phone||'—'}</b></span><span>Skills<b>{data.skills||'—'}</b></span></div></div></div>}</>}
function EmptyPage({title,subtitle,icon:Icon}) { return <><div className="page-head"><div><span className="eyebrow">OPERATIONS</span><h2>{title}</h2><p>{subtitle}</p></div><button className="primary">+ Schedule {title.slice(0,-1)}</button></div><div className="empty"><Icon size={34}/><h3>No {title.toLowerCase()} yet</h3><p>Live records will appear here when available from the backend.</p></div></> }
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
